export const enum AppRoute {
  Profile = '/profile',
  Dashboard = '/dashboard',
  Training = '/training',
  FoodCategories = '/food',
  Food = '/food/:categoryId',
  Communication = '/communication',
  Quiz = '/quiz',
  Result = '/result',
  Begin = '/begin',
  Parameters = '/parameters',
  Record = '/record',
  Lectures = '/lectures',
  Recipes = '/recipes',
}
