export const enum AppRoute {
  Start = '/',
  Profile = '/profile',
  Dashboard = '/dashboard',
  Training = '/training',
  FoodCategories = '/food',
  Food = '/food/:categoryId',
  Communication = '/communication',
  Quiz = '/quiz',
  Result = '/result',
  Begin = '/begin',
  Parameters = '/parameters',
  Record = '/record',
  LecturesWeeks = '/lectures',
  LectureWeek = '/lectures/:week',
  LectureDetails = '/lectures/:week/:id',
  RecipeCategories = '/recipes',
  RecipeCategory = '/recipes/:category',
  RecipeDetails = '/recipes/:category/:id',
  NoEntry = '/no-entry',
}
