export const measurementsInputs = [
  {
    name: 'weight',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Вес',
    postfix: 'кг',
  },
  {
    name: 'chest',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Грудь',
    postfix: 'см',
  },
  {
    name: 'waist',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Талия',
    postfix: 'см',
  },
  {
    name: 'abdominalCircumference',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Живот',
    postfix: 'см',
  },
  {
    name: 'hips',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Бёдра',
    postfix: 'см',
  },
  {
    name: 'legs',
    type: 'number',
    inputMode: 'decimal',
    step: 0.1,
    label: 'Нога',
    postfix: 'см',
  },
] as const;
